Fixed issue regarding Supportable and SupportOffsetWhileReloading
cortex-command-community/Cortex-Command-Community-Project pull request #107
Opened 2024-02-20 13:20 UTC by Alejandroibo

If a gun had SupportOffsetWhileReloading == true and you modified it's Supportable value to be only true while reloading (and false when not), the hand wouldn't support the gun on the reload. 

The one handed penalty is still applied to the reload, since the gun reloads quicker than the hand reaches the gun. 
Nothing a few lines of code in lua to restrict the reload can't fix for modders that care about it

2024-02-20 15:51 UTC, Alejandroibo commented
I've found another bug present with the Supportable value ,however I'm a bit stumped as how to fix it:
Let's say that I have a gun A with Supportable = 0. If you switch to it for the first time, your offhand will go the arm's IdleOffset (Intented behaviour)
If now I change to another gun B with Supportable = 1, and then switch back to gun A, now the offhand is stuck trying to reach the last position of gun B's supportOffset, instead of going back to the arm's IdleOffset like before.

2024-02-21 10:27 UTC, MageKing17 requested changes

2024-02-21 10:27 UTC, MageKing17 commented on Source/Entities/AHuman.cpp
> +					} else if (!bgDevice && (!heldDevice->IsReloading() || (heldDevice->IsReloading() && heldDevice->GetUseSupportOffsetWhileReloading())) && heldDevice->IsSupportable()) {
Checking `IsReloading()` twice is redundant.
```suggestion
					} else if (!bgDevice && (!heldDevice->IsReloading() || heldDevice->GetUseSupportOffsetWhileReloading()) && heldDevice->IsSupportable()) {
```

2024-02-21 10:48 UTC, MageKing17 approved these changes

2024-02-21 10:57 UTC, MageKing17 commented
As far as the second problem goes, it looks like the problem is that `m_HeldDeviceThisArmIsTryingToSupport` is never checked to see if that device is actually, you know... held. The conditional on line 2268 could easily have an `|| !m_pBGArm->GetHeldDeviceThisArmIsTryingToSupport()->IsBeingHeld()` added to it.

2024-02-21 18:56 UTC, MageKing17 submitted a review, later dismissed

2024-02-21 19:25 UTC, Causeless approved these changes

2024-02-21 19:39 UTC, Causeless approved these changes

2024-02-21 22:54 UTC, merged